services:
  mysql:
    image: mysql:9.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
      - MYSQL_DATABASE=test_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/1.sql

