services:
  mysql:
    image: mariadb:11.7.2
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ROOT_USER=root
      - MARIADB_USER=test_user
      - MARIADB_PASSWORD=test_pass
      - MARIADB_DATABASE=test_db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1s
      timeout: 5s
      retries: 6
      start_period: 15s
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/1.sql
  wait-for-db:
    image: mysql:9.3.0
    volumes:
      - ./wait_for_db.sh:/wait_for_db.sh
    entrypoint: /wait_for_db.sh
    environment:
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
    healthcheck:
      test: ["CMD-SHELL", "if test -f /tmp/db_ready; then exit 0 ; else exit 1; fi"]
      interval: 1s
      timeout: 5s
      retries: 60
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
