services:
  mysql:
    image: mysql:9.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
      - MYSQL_DATABASE=test_db
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/1.sql

